#pragma once
enum ToggleReading{
    // Top for operational toggle, bottom for maintenance toggle
   // CENTER
    AUTOMATIC_MODE,
    NEUTRAL_MODE,

    // RIGHT
    MAINTENANCE_MODE,
    FORWARD_MODE,

    // LEFT
    CONTINUOUS_MODE,
    REVERSE_MODE
};

enum FiniteState{
    IDLE, // IDLE BLOCKED
    READY, // IDLE READY
    REVERSE, // REVERSE BLOCKED
    DISPATCHED, // DISPATCHED BLOCKED
    DISPATCHED_2,
    FORWARD, // FORWARD BLOCKED
    IDLE_MAINT, // IDLE MAINTENANCE
    REVERSE_MAINT, // REVERSE MAINTENANCE
    FORWARD_MAINT, // FORWARD MAINTENANCE
    EMERGENCY, // IDLE EMERGENCY
};
